### ISSUE TITLE
Cannot customize the chemical composition of the materials

### ISSUE THREAD

**Issue by Death-slash** [civilwargeeky/CEA_Wrap#2]
Thank you so much for the time and effort you put into this project. This wrapper helped me a lot because I need to use python loop to call CEA for calculating the combustion temperature under the HP problem. 
However, the program reported errors when I customize the chemical composition and enthalpy of formation of the material to calculate the combustion temperature more conveniently and freely. 
Here is my code:
PBT = Fuel("pbt", wt_percent=20, chemical_composition="C 37.33 H 66.73 N 24.89 O 8.48", hf=1185)
A3 = Fuel("a3", wt_percent=20, chemical_composition="C 2.4 H 4.1 O 3.1 N 1.3", hf=-1927.01)
AN = Oxidizer("an", wt_percent=57, chemical_composition="N 1 H 4 N 1 O 3", hf=-4129.7)
KN = Oxidizer("kn", wt_percent=3, chemical_composition="K 1 N 1 O 3", hf=-4892.51)
The errors is as follows:
> File "C:\ProgramData\Anaconda3\lib\site-packages\CEA_Wrap\CEA.py", line 227, in run
    self.make_input_file(self.materials)
  File "C:\ProgramData\Anaconda3\lib\site-packages\CEA_Wrap\CEA.py", line 262, in make_input_file
    file.write(fuel.get_CEA_str())
  File "C:\ProgramData\Anaconda3\lib\site-packages\CEA_Wrap\CEA.py", line 95, in get_CEA_str
    string += " h,kj/mol={:0.5}".format(self.hf)
ValueError: Precision not allowed in integer format specifier

Regards

**Comment by civilwargeeky** [comment]
Hello,

Thanks for reaching out to me about this problem. Hopefully you figured it out over the weekend, but all you needed to do was change your "hf=1185" to "hf=1185.0" in your PBT definition.

All I needed to fix this on my end is changing line 95 from `" h,kj/mol={:0.5}"` to `" h,kj/mol={:0.5f}"` to cast the int to a float
You will note that when you try running your problem, it will fail with a cryptic error because your reactants have a lot of condensed phase products.
I have fixed the formatting, added a better error message, and a few other things with 7f8e542b7ec1676e95c37ee59006cf6d6aa56ce0 . I recommend redownloading with pip.

**Comment by Death-slash** [comment]
Amazing! Thanks for answering my question, I modified the code and it works fine, by the way, is the unit of hf kJ/kg or kJ/mol? Because I see "h, kJ/mol" in the error message.

**Comment by civilwargeeky** [comment]
Ooh, that is a good catch. That's an error in my documentation.
I believe CEA accepts either /mol or /kg, but I do specify on /mol, rather than /kg like I say in the documentation. I will fix that tomorrow and add a switch for kg or mol in the future

**Comment by Death-slash** [comment]
Thanks again! I am done with my code.
